### ISSUE TITLE
`StrMap` and `Map String` instances inconsistent

### ISSUE THREAD

**Issue by Risto-Stevcev** [purescript/purescript-maps#123] opened 2017-08-27 16:08 UTC
why does `StrMap` have stricter instances than `Map String`?

`￼￼￼(Ord k) => Monoid (Map k v)`
vs
`(Semigroup a) => Monoid (StrMap a)`

￼￼￼￼in this case `StrMap` is stricter, because `Monoid (Map String v)` doesn't restrict `v` in any way

Shouldn't `StrMap` and `Map String` have the same kind of instances? or at least worst-case `StrMap` should have less strict instances because the key is known to be `String`?

**Comment by hdgarrood** [comment] 2017-08-27 16:12
I think this is a duplicate of https://github.com/purescript/purescript-maps/issues/94?

**Comment by paf31** [comment] 2017-08-27 22:07
Yes

**Closed by paf31** 2017-08-27 22:07 UTC
